import { useState } from 'react'
import { useReportHistory } from './useReportHistory'
import type { Report } from '../../types/report'

/** FR-019: retention tab — past reports generated by the current user. */
export function ReportHistory() {
  const { reports, loading, error, getSignedUrl } = useReportHistory()

  if (loading) return <p className="text-sm text-gray-500">Loading report history…</p>
  if (error)
    return (
      <p role="alert" className="text-sm text-red-600">
        Failed to load report history: {error}
      </p>
    )

  return (
    <div className="rounded border p-3" data-testid="report-history">
      <h3 className="text-sm font-semibold">Report history</h3>
      <ul className="text-sm">
        {reports.map((r) => (
          <ReportHistoryRow key={r.id} report={r} getSignedUrl={getSignedUrl} />
        ))}
        {reports.length === 0 && <li className="text-gray-500">No reports generated yet.</li>}
      </ul>
    </div>
  )
}

function ReportHistoryRow({
  report,
  getSignedUrl,
}: {
  report: Report
  getSignedUrl: (path: string) => Promise<string | null>
}) {
  const [signedUrl, setSignedUrl] = useState<string | null>(null)

  return (
    <li>
      {new Date(report.generated_at).toLocaleString()} — {report.report_type} ({report.audience})
      {report.pdf_url &&
        (signedUrl ? (
          <>
            {' · '}
            <a
              href={signedUrl}
              target="_blank"
              rel="noreferrer"
              className="text-blue-700 underline"
            >
              Open PDF
            </a>
          </>
        ) : (
          <>
            {' · '}
            <button
              type="button"
              className="text-blue-700 underline"
              onClick={async () => setSignedUrl(await getSignedUrl(report.pdf_url!))}
            >
              Get PDF link
            </button>
          </>
        ))}
    </li>
  )
}
